GET http://localhost:8080/actuator/health
Accept: application/json

###

GET http://localhost:8080/actuator
Accept: application/json

###

GET http://localhost:8080/api/greet
Accept: application/json

###

GET http://localhost:8080/api/greet
Accept: application/json
Authorization: Bearer <jwt_token>

###
