GET http://localhost:8080/actuator/health
Accept: application/json

###

GET http://localhost:8080/actuator
Accept: application/json

###

GET http://localhost:8080/api/greet
Accept: application/json

###

GET http://localhost:8080/api/greet
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.ew0KInN1YiI6ImFuaXNoLnBhbnRoaUBobXMuY29tIiwNCiJhdWQiOiJnZW5lcmljIiwNCiJ1aWQiOiJ0MTU4OTA5IiwNCiJnaXZlbk5hbWUiOiJBbmlzaCIsDQoic24iOiJQYW50aGkiLA0KIm1haWwiOiJhbmlzaC5wYW50aGlAaG1zLmNvbSIsDQoiZGlzcGxheU5hbWUiOiJQYW50aGksIEFuaXNoIiwNCiJlY2VudGVyYWNjb3VudG5hbWUiOiJ0MTU4OTA5IiwNCiJobXNsb2dpbiI6InQxNTg5MDkiLA0KImlhdCI6MTcwNzA2MDQ1MSwNCiJleHAiOjE3MDcwNjE5NTEsDQoibmJmIjoxNzA3MDYwMzMxDQp9.CdysqvU9FzRTYVPV6mJI9Mtm97URzY12uZ71td8lc5MMzfRtUKcuaF4vQflwltz0Eo3rTmWoDCokQUpiF5lIm2_-jOyTZfoSvDFWVRNDYe9zBSsfKpE42BaiISJDKNdjqkU3jzgLwCvRdRQFv9YQM_TVAn5xQYJqUUmoTcx__kuSzMaL9-5FeuOjc-hAURlyCRR7S4q1sOioam8FBQbOfWA5d_Mloj670b6-GhjJw1z7jvTjmJ3W9rA3ApwOBhtGelntW3TFSp2ROuJ9TRhT2-bcseK_Bdhvm_B1S6N53GnpxuRYrPI3oqeEcvGLyfWf4Dz4Psw74JOhVtFeR5aoJA
auth-type: nonOAuth
###
