GET http://localhost:8080/actuator/health
Accept: application/json

###

GET http://localhost:8080/actuator
Accept: application/json

###

GET http://localhost:8080/api/greet
Accept: application/json

###

GET http://localhost:8080/api/greet
Accept: application/json
Authorization: Bearer eyJraWQiOiJuVURKd2pVYW1Xa012TFBiOGFXdkZqTTJ6c3EwN00zcFZZdlZyMjAzLUtnIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULmtJaE85OTktZEpUQTEwdjlnVFEyajhJS3lNdndBSzhFNVREUU9UYjE3RWMiLCJpc3MiOiJodHRwczovL2Rldi0wOTk4MDQxNy5va3RhLmNvbS9vYXV0aDIvZGVmYXVsdCIsImF1ZCI6ImFwaTovL2RlZmF1bHQiLCJpYXQiOjE3MDU2MjEyMTMsImV4cCI6MTcwNTYyNDgxMywiY2lkIjoiMG9hZWp2OHV4dURQdWMyYXQ1ZDciLCJzY3AiOlsibXlfZGF0YSJdLCJzdWIiOiIwb2FlanY4dXh1RFB1YzJhdDVkNyJ9.hVk-afGSkN8TGvLZPCOo6WJ22aBB2DCfG74-dhzRM4L4mmZAO02xChJMsZoQq6c3cDVPY8SWbmQMI0xvYDW344oQ3dekV7PhxYW12V4RAx-WU8NEE7bGhAHP2Gfb78eyxmw1jMK7Ev6WbQCqW7zdS8Z8mZ6hF7HFYxEjDTPTysPu1Mm3qISNvY7vw_bsXwwN9G9WjjYAxlIivHImYlkLUSUUxu6zd8wQiaQG_R-_Tc6eKgvLbTjZdkyerbF6R1a25K9R9Da8VoDEOblY-hpyyq8cno239MRR31lTjQXJCwg4DFrySy_CtrOtb-1PTnCDafBlmKWjO9uvtCuEWGbyIw

###
