management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.security: debug
    dev.app.resource.server: debug

spring:
  security:
    oauth2:
      client:
        provider:
          azure-ad:
            issuer-uri: https://login.microsoftonline.com/1b286c40-c2fd-46d5-a553-b6502b89f42d/v2.0
          okta:
            issuer-uri: https://dev-09980417.okta.com
          azure-b2c:
            authorization-uri: https://{tenant}.b2clogin.com/{tenant}.onmicrosoft.com/{policy}/oauth2/v2.0/authorize
            jwk-set-uri: https://{tenant}.b2clogin.com/{tenant}.onmicrosoft.com/{policy}/discovery/v2.0/keys
            token-uri: https://{tenant}.b2clogin.com/{tenant}.onmicrosoft.com/{policy}/oauth2/v2.0/token
        registration:
          azure-b2c:
            provider: azure-b2c
            client-id:
            client-secret:
            scope: openid, email
            redirect-uri: http://localhost:8080/login/oauth2/code/azure-b2c
            client-name: Microsoft B2C Login
            authorization-grant-type: authorization_code
          azure-ad:
            provider: azure-ad
            client-id:
            client-secret:
            scope: openid, profile, email, offline_access
            redirect-uri: http://localhost:8080/login/oauth2/code/azuread
            client-name: Microsoft Entra ID (Azure AD)
          okta:
            provider: okta
            client-id:
            client-secret:
            scope: openid, profile, email, offline_access
            redirect-uri: http://localhost:8080/login/oauth2/code/okta
            client-name: Okta
