management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.security: debug
    dev.app.resource.server: debug

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: <replace_with_jwk_url>
          issuer-uri: <replace_with_issuer_url>
