management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.security: debug
    dev.app.resource.server: debug

spring:
  security:
    oauth2:
      client:
        provider:
          azure:
            issuer-uri: '***'     # https://login.microsoftonline.com/{tenantId}/v2.0
          okta:
            issuer-uri: '***'     # https://{yourOktaDomain}/oauth2/default
        registration:
          azure:
            provider: azure
            client-id: '***'      # Application (client) ID
            client-secret: '***'  # Client secret
            scope: openid, profile, email, offline_access
            redirect-uri: http://localhost:8080/login/oauth2/code/azuread
            client-name: Microsoft Entra ID
          okta:
            provider: okta
            client-id: '***'      # Client ID
            client-secret: '***'  # Client secret
            scope: openid, profile, email, offline_access
            redirect-uri: http://localhost:8080/login/oauth2/code/okta
            client-name: Okta
