management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.security: debug
    dev.app.resource.server: debug

spring:
  security:
    oauth2:
      client:
        provider:
          azure:
            issuer-uri: '***'
        registration:
          azure:
            provider: azure
            client-id: '***'
            client-secret: '***'
            scope: openid, profile, email, offline_access
            redirect-uri: http://localhost:8080/login/oauth2/code/
